# -*- coding: utf-8 -*-
"""lidc_preprocesing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5M1xw3tjDB89gJt1fwyIwChi2v80qou
"""

from pathlib import Path
import numpy as np
import pandas as pd
from tqdm import tqdm
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import drive

drive.mount('/content/drive')

base_path = Path('/content/drive/MyDrive/Rare Lung Nodules/LIDC-IDRI-slices')
output_dir = Path('/content/drive/MyDrive/Rare Lung Nodules/preprocessed_lidc/')
output_dir.mkdir(exist_ok=True)

print("✅ Ready to process your exact structure!")

# Enable T4 GPU (faster later for models)
import torch
print(f"GPU available: {torch.cuda.is_available()}")
print(f"GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None'}")

# Runtime → Change runtime type → T4 GPU (if not already)

records = []

print("🔍 Scanning your nodule folders...")

total_patients = len(list(base_path.glob('LIDC-IDRI-*')))
print(f"📊 Total patients found: {total_patients}")

patient_count = 0
nodule_count = 0
slice_count = 0

for patient_folder in tqdm(base_path.glob('LIDC-IDRI-*'), desc="Patients", total=total_patients):
    patient_count += 1
    print(f"\n👤 Patient {patient_count}/{total_patients}: {patient_folder.name}")

    nodule_folders = list(patient_folder.glob('nodule-*'))
    print(f"   📦 Found {len(nodule_folders)} nodule folders")

    nodule_processed = 0
    for nodule_folder in nodule_folders:
        nodule_count += 1
        img_dir = nodule_folder / 'images'

        if not img_dir.exists():
            print(f"   ❌ No images in {nodule_folder.name}")
            continue

        # Find ALL mask folders for this nodule
        mask_dirs = list(nodule_folder.glob('mask-*'))

        if not mask_dirs:
            print(f"   ❌ No masks in {nodule_folder.name}")
            continue

        # Use FIRST mask folder (mask-0) per nodule
        mask_dir = mask_dirs[0]
        print(f"   ✅ Using mask folder: {mask_dir.name}")

        # Get slice files (slice-0.png, slice-1.png, etc.)
        img_files = sorted(img_dir.glob('slice-*.png'))
        mask_files = sorted(mask_dir.glob('slice-*.png'))

        print(f"      🖼️  Images: {len(img_files)}, Masks: {len(mask_files)}")

        # Pair by index (slice 0 → slice 0, etc.)
        min_slices = min(len(img_files), len(mask_files))
        slice_count += min_slices

        for slice_idx in range(min_slices):
            records.append({
                'patient_id': patient_folder.name,
                'nodule_id': nodule_folder.name,
                'slice_idx': slice_idx,
                'img_path': str(img_files[slice_idx]),
                'mask_path': str(mask_files[slice_idx]),
                'label': 1  # Nodule slice = positive
            })

        nodule_processed += 1
        if nodule_processed % 10 == 0:
            print(f"   📈 Progress: {nodule_processed}/{len(nodule_folders)} nodules")

    print(f"   ✅ Patient complete: {nodule_processed} nodules processed")

print(f"\n🎉 SCAN COMPLETE!")
print(f"📊 Patients: {patient_count}/{total_patients}")
print(f"📦 Nodules scanned: {nodule_count}")
print(f"🖼️  Total image-mask pairs: {len(records)}")
print(f"📈 Pairs per patient avg: {len(records)/max(patient_count,1):.1f}")

import torch
import numpy as np
from PIL import Image
from pathlib import Path
from tqdm import tqdm
import pandas as pd
import gc  # Memory management

# T4 GPU check
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"🚀 Using device: {device}")
print(f"GPU memory: {torch.cuda.memory_allocated()/1e9:.1f}GB / {torch.cuda.memory_reserved()/1e9:.1f}GB")

print("🔄 Standardizing to PyTorch format on T4 GPU...")

dataset = []
batch_size = 32  # GPU batch processing
batches = len(records) // batch_size + 1

for batch_idx in tqdm(range(batches), desc="GPU Batches"):
    batch_start = batch_idx * batch_size
    batch_end = min((batch_idx + 1) * batch_size, len(records))
    batch_records = records[batch_start:batch_end]

    # GPU tensors for batch
    imgs_gpu = []
    masks_gpu = []
    metadata = []

    for i, rec in enumerate(batch_records):
        try:
            # Load PNGs (CPU)
            img = np.array(Image.open(rec['img_path']))
            mask = np.array(Image.open(rec['mask_path']))

            # Normalize
            img = img.astype(np.float32) / 255.0
            mask = (mask > 127).astype(np.float32)

            # To GPU tensor (CHW)
            img_tensor = torch.from_numpy(np.expand_dims(img, 0)).to(device)
            mask_tensor = torch.from_numpy(np.expand_dims(mask, 0)).to(device)

            imgs_gpu.append(img_tensor)
            masks_gpu.append(mask_tensor)

            # Filename
            fname = f"p{rec['patient_id'][-4:]}_n{rec['nodule_id'][-1]}_s{rec['slice_idx']:03d}"
            metadata.append({
                'fname': fname,
                'patient_id': rec['patient_id'],
                'nodule_id': rec['nodule_id'],
                'slice_idx': rec['slice_idx'],
                'label': rec['label'],
                'is_small': 1,
                'batch': batch_idx
            })

        except Exception as e:
            print(f"⚠️  Skip {rec['img_path']}: {e}")
            continue

    if imgs_gpu:
        # Stack batch on GPU
        batch_imgs = torch.stack(imgs_gpu)
        batch_masks = torch.stack(masks_gpu)

        print(f"  📦 Batch {batch_idx+1}/{batches}: {batch_imgs.shape} tensors on GPU")
        print(f"     GPU memory: {torch.cuda.memory_allocated()/1e9:.1f}GB")

        # Move back to CPU & save
        batch_imgs_cpu = batch_imgs.cpu().numpy()
        batch_masks_cpu = batch_masks.cpu().numpy()

        for j, (img_cpu, meta) in enumerate(zip(batch_imgs_cpu, metadata)):
            fname = meta['fname']

            # Save NPY (CHW format)
            np.save(output_dir / f"{fname}_img.npy", img_cpu.astype(np.float32))
            np.save(output_dir / f"{fname}_mask.npy", batch_masks_cpu[j].astype(np.float32))

            dataset.append(meta)

        # Clear GPU memory
        del batch_imgs, batch_masks, imgs_gpu, masks_gpu
        torch.cuda.empty_cache()
        gc.collect()

# Final metadata
df = pd.DataFrame(dataset)
if len(df) > 0:
    # FL client splits (stratified by patient ID)
    df['client_id'] = pd.qcut(df['patient_id'].astype(str).str.extract(r'(\d+)')[0].astype(int),
                              5, labels=False, duplicates='drop').astype(int)
    df.to_csv(output_dir / 'dataset_ready.csv', index=False)

    print(f"\n🎉 SUCCESS! {len(df)} slices processed on T4 GPU!")
    print(f"📊 GPU peak memory used: {torch.cuda.max_memory_allocated()/1e9:.1f}GB")
    print("\nClient distribution:")
    print(df['client_id'].value_counts().sort_index())
    print("\nFirst 5 rows:")
    print(df.head())

    # Summary stats
    print(f"\n📈 Dataset summary:")
    print(f"   Total slices: {len(df):,}")
    print(f"   Patients: {df['patient_id'].nunique()}")
    print(f"   Positive labels: {df['label'].sum()}")
else:
    print("❌ No data processed - check paths")

print(f"\n✅ Files saved to: {output_dir}")
print("Next: PyTorch Dataset + U-Net training!")

import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
import pandas as pd

# Reload dataset (safe)
output_dir = Path('/content/drive/MyDrive/Rare Lung Nodules/preprocessed_lidc/')
df = pd.read_csv(output_dir / 'dataset_ready.csv')
print(f"📊 Loaded {len(df)} slices from {df['patient_id'].nunique()} patients")

# Show first 6 pairs
fig, axs = plt.subplots(3, 6, figsize=(24, 12)) # Changed 4 to 6 columns

for i in range(min(6, len(df))):
    row = df.iloc[i]
    img_path = output_dir / f"{row['fname']}_img.npy"
    mask_path = output_dir / f"{row['fname']}_mask.npy"

    # Load safely
    img = np.load(img_path)[0]  # First channel
    mask = np.load(mask_path)[0]

    # Image only
    axs[0, i].imshow(img, cmap='gray')
    axs[0, i].set_title(f"P{row['patient_id'][-4:]}")
    axs[0, i].axis('off')

    # Overlay
    axs[1, i].imshow(img, cmap='gray', alpha=0.7)
    axs[1, i].imshow(mask, alpha=0.6, cmap='Reds')
    axs[1, i].set_title(f"N{row['nodule_id'][-1]} S{row['slice_idx']}")
    axs[1, i].axis('off')

    # Stats row
    axs[2, i].axis('off')
    axs[2, i].text(0.1, 0.5, f"Client: {row['client_id']}\nLabel: {row['label']}\nSmall: {row['is_small']}",
                   transform=axs[2, i].transAxes, fontsize=12, va='center')

plt.suptitle('Your Preprocessed Dataset Preview', fontsize=16)
plt.tight_layout()
plt.savefig(output_dir / 'dataset_preview.png', dpi=150, bbox_inches='tight')
plt.show()

print("✅ Visualization complete!")
print(f"📁 Preview saved: {output_dir / 'dataset_preview.png'}")
print(f"📊 Ready for U-Net training (15,548 slices)!")