"""
app_core/config.py
Centralised configuration for the RareNoduleFL Gradio app.
All paths are repo-relative. No Google Drive or Colab assumptions.
"""

from pathlib import Path

# ── Repo root (two levels up from this file: app_core/ → repo root) ──────────
REPO_ROOT = Path(__file__).parent.parent

# ── Result assets ─────────────────────────────────────────────────────────────
RESULTS_DIR = REPO_ROOT / "results"

# Figures — paper figures generated by evaluation/complete_project_finish.py
FIGURES = {
    "pipeline":       RESULTS_DIR / "pipeline_overview.png",
    "learning_curves":RESULTS_DIR / "fl_learning_curves.png",
    "client_drift":   RESULTS_DIR / "fl_client_drift.png",
    "ece_comparison": RESULTS_DIR / "fl_ece_comparison.png",
    "entropy_maps":   RESULTS_DIR / "xai_entropy_heatmaps.png",
    "gradcam_panels": RESULTS_DIR / "xai_gradcam_panels.png",
    "hetero_bars":    RESULTS_DIR / "fl_heterogeneity_bars.png",
    "froc_curve":     RESULTS_DIR / "froc_curve_fixed.png",   # corrected version
    "froc_fallback":  RESULTS_DIR / "froc_curve.png",         # fallback if fixed missing
    "calibration":    RESULTS_DIR / "calibration_analysis.png",
}

# Tables
ABLATION_CSV    = RESULTS_DIR / "fl_ablation_table.csv"
STAT_TESTS_TXT  = RESULTS_DIR / "fl_statistical_tests.txt"
FROC_DATA_CSV   = RESULTS_DIR / "froc_data_fixed.csv"
CALIB_STATS_CSV = RESULTS_DIR / "model_calibration_stats_fixed.csv"

# ── Model checkpoints ─────────────────────────────────────────────────────────
MODELS_DIR = REPO_ROOT / "models"

CHECKPOINT_PATHS = {
    "Central U-Net":       MODELS_DIR / "step4.1_unet_best.pth",
    "FL IID (FedAvg)":     MODELS_DIR / "fl_iid_global_best.pth",
    "FL Non-IID + RUS":    MODELS_DIR / "fl_noniid_rus_global_best.pth",
}

# State dict key name differs between central and FL checkpoints
CHECKPOINT_SD_KEY = {
    "Central U-Net":    "model_state_dict",
    "FL IID (FedAvg)":  "global_model_state_dict",
    "FL Non-IID + RUS": "global_model_state_dict",
}

# ── Architecture constants — must exactly match training checkpoints ───────────
IMAGE_SIZE  = 256
IN_CHANNELS = 1
OUT_CHANNELS = 1
UNET_CHANNELS  = (32, 64, 128, 256, 512)
UNET_STRIDES   = (2, 2, 2, 2)
UNET_RES_UNITS = 2

# ── Sample images ─────────────────────────────────────────────────────────────
SAMPLES_DIR = REPO_ROOT / "assets" / "samples"

SAMPLE_CASES = [
    {
        "name":    "Sample 01 — Small nodule, pleural region",
        "file":    SAMPLES_DIR / "sample_01.png",
        "caption": "Rare nodule (<10mm) near pleural surface",
    },
    {
        "name":    "Sample 02 — Central nodule, clear margin",
        "file":    SAMPLES_DIR / "sample_02.png",
        "caption": "Well-defined central nodule, standard size",
    },
    {
        "name":    "Sample 03 — Ground-glass opacity pattern",
        "file":    SAMPLES_DIR / "sample_03.png",
        "caption": "Ground-glass nodule appearance, diffuse boundary",
    },
]

# ── App identity ──────────────────────────────────────────────────────────────
APP_TITLE    = "RareNoduleFL"
APP_SUBTITLE = (
    "Privacy-Preserving Federated Learning for "
    "Rare Lung Nodule Detection"
)
APP_DESCRIPTION = (
    "An end-to-end research system trained across 5 simulated hospital "
    "silos on LIDC-IDRI using FedAvg with Rare Uncertainty Sensitivity "
    "(RUS) loss, Grad-CAM++ explainability, and FROC evaluation."
)

# ── Display constants ─────────────────────────────────────────────────────────
DEFAULT_MODEL   = "FL Non-IID + RUS"
DEFAULT_THRESHOLD = 0.5
MODEL_KEYS      = list(CHECKPOINT_PATHS.keys())

# Known metrics (from confirmed training logs — displayed even without checkpoints)
KNOWN_METRICS = {
    "Central U-Net": {
        "dice": 0.8445, "sensitivity": 0.9089,
        "froc_1fp": 0.355, "ece": 0.0103,
        "description": "Centralised training on all 700 patients. "
                       "Highest Dice but not privacy-preserving.",
    },
    "FL IID (FedAvg)": {
        "dice": 0.7674, "sensitivity": 0.8214,
        "froc_1fp": 0.959, "ece": 0.00063,
        "description": "FedAvg across 5 IID clients. "
                       "Lower Dice but 96× better calibration (ECE).",
    },
    "FL Non-IID + RUS": {
        "dice": 0.7664, "sensitivity": 0.8128,
        "froc_1fp": 0.962, "ece": 0.00065,
        "description": "Non-IID heterogeneous clients + RUS loss. "
                       "Best FROC. McNemar p=0.021 confirms RUS effect.",
    },
}

# Statistical highlights for the About tab
STAT_HIGHLIGHTS = [
    ("96.2%",  "Detection sensitivity @1FP/scan (FL+RUS FROC)"),
    ("16×",    "ECE improvement: central 0.0103 → FL 0.00063"),
    ("p=0.021","McNemar: RUS significantly changes rare-nodule predictions"),
    ("p=0.708","Paired t-test: RUS does NOT degrade overall Dice"),
    ("700",    "LIDC-IDRI patients across 5 federated clients"),
    ("15k",    "CT slices, 256×256, preprocessed to NPY"),
]
