# -*- coding: utf-8 -*-
"""step6_optimise_m1_target90_m3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrZlFHgZOFQGkr63lP-_vq-YLgXWVMnx
"""

# ============================================================================
# 0. INSTALL DEPENDENCIES
# ============================================================================
print("📦 Installing dependencies ...")
import subprocess, sys

subprocess.run([
    sys.executable, "-m", "pip", "install",
    "torch==2.6.0", "torchvision==0.21.0", "torchaudio==2.6.0",
    "--index-url", "https://download.pytorch.org/whl/cu121", "-q"
], check=False)
subprocess.run([
    sys.executable, "-m", "pip", "install",
    "monai==1.5.0", "numpy==1.26.4", "pandas==2.2.0",
    "scikit-learn==1.4.0", "tqdm", "-q"
], check=False)
print("✅ Dependencies ready. If you see import errors restart runtime once.")

# ============================================================================
# 1. MOUNT DRIVE
# ============================================================================
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# ============================================================================
# 2. PATHS  —  *** adjust only if your Drive folder differs ***
# ============================================================================
from pathlib import Path

BASE_DIR  = Path("/content/drive/MyDrive/Rare Lung Nodules")
DATA_DIR  = BASE_DIR / "preprocessed_lidc"   # client_0_iid.csv … test_iid.csv + .npy files
MODEL_DIR = BASE_DIR / "models"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

print(f"✅ BASE : {BASE_DIR}")
print(f"✅ DATA : {DATA_DIR}")
print(f"✅ MODELS: {MODEL_DIR}")

# ============================================================================
# 3. IMPORTS
# ============================================================================
import torch, json, warnings, numpy as np, pandas as pd
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch.cuda.amp import autocast, GradScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm

from monai.networks.nets import UNet, SwinUNETR
from monai.networks.layers import Norm
from monai.losses import DiceCELoss
from monai.transforms import (
    Compose, RandFlipd, RandRotate90d, RandAffined,
    RandAdjustContrastd, RandGaussianNoised, RandZoomd,
    RandGaussianSmoothd, ToTensord, ScaleIntensityd,
)

warnings.filterwarnings("ignore")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\n✅ Device : {device}")
if device.type == "cuda":
    gpu_name = torch.cuda.get_device_name(0)
    gpu_mem  = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"   GPU    : {gpu_name}  ({gpu_mem:.1f} GB)")
    # Pick batch-size that fits any GPU safely
    BATCH_SIZE = 48 if gpu_mem >= 35 else (32 if gpu_mem >= 20 else 16)
else:
    BATCH_SIZE = 8
print(f"   Batch  : {BATCH_SIZE}")

# ============================================================================
# 4. DATASET
# ============================================================================

class LIDCNoduleDataset(Dataset):
    def __init__(self, data_df: pd.DataFrame, data_dir: Path,
                 is_train: bool = True, augment_rare: bool = False,
                 client_noise_sigma: float = 15.0):
        self.data_dir = Path(data_dir)
        self.is_train = is_train
        self.client_noise_sigma = client_noise_sigma

        if augment_rare and is_train:
            rare = data_df[data_df["is_small"] == 1]
            data_df = pd.concat([data_df, rare, rare], ignore_index=True)
            print(f"  ✅ Rare boost: {len(rare)} small nodules × 3")

        self.data_df = data_df.reset_index(drop=True)
        self.transform = self._build_transforms(is_train)
        print(f"  📊 Dataset: {len(self.data_df)} samples  [train={is_train}]")

    def _build_transforms(self, is_train: bool) -> Compose:
        if is_train:
            return Compose([
                RandFlipd(keys=["image","mask"], prob=0.5, spatial_axis=0),
                RandFlipd(keys=["image","mask"], prob=0.5, spatial_axis=1),
                RandRotate90d(keys=["image","mask"], prob=0.5, max_k=3),
                RandAffined(keys=["image","mask"], prob=0.6,
                            rotate_range=(np.pi/12, np.pi/12),
                            scale_range=(0.15, 0.15),
                            translate_range=(10, 10),
                            mode=["bilinear","nearest"],
                            padding_mode="border"),
                RandZoomd(keys=["image","mask"], prob=0.4,
                          min_zoom=0.85, max_zoom=1.15,
                          mode=["bilinear","nearest"]),
                RandGaussianNoised(keys=["image"], prob=0.5, mean=0.0,
                                   std=self.client_noise_sigma / 255.0),
                RandGaussianSmoothd(keys=["image"], prob=0.3,
                                    sigma_x=(0.5, 1.5), sigma_y=(0.5, 1.5)),
                RandAdjustContrastd(keys=["image"], prob=0.5, gamma=(0.80, 1.20)),
                ScaleIntensityd(keys=["image"], minv=0.0, maxv=1.0),
                ToTensord(keys=["image","mask"]),
            ])
        else:
            return Compose([
                ScaleIntensityd(keys=["image"], minv=0.0, maxv=1.0),
                ToTensord(keys=["image","mask"]),
            ])

    def __len__(self): return len(self.data_df)

    def __getitem__(self, idx):
        row      = self.data_df.iloc[idx]
        fname    = row["fname"]
        img_path = self.data_dir / f"{fname}_img.npy"
        msk_path = self.data_dir / f"{fname}_mask.npy"
        try:
            image = np.load(img_path).astype(np.float32)
            mask  = np.load(msk_path).astype(np.float32)
        except Exception as e:
            print(f"⚠️  Load error {fname}: {e}")
            image = np.zeros((1, 256, 256), dtype=np.float32)
            mask  = np.zeros((1, 256, 256), dtype=np.float32)

        d = self.transform({"image": image, "mask": mask})
        d["label"]    = torch.tensor(row["label"], dtype=torch.long)
        # Re-derive is_small from mask pixel count at runtime — do NOT trust the
        # CSV is_small column, which defaults to 1 for ALL samples when the Excel
        # file was missing during preprocessing. A nodule mask covering fewer than
        # 200 pixels (≈ diameter < ~16px ≈ <10mm at typical resolution) is "small".
        mask_pixels   = float((mask > 0.5).sum())
        csv_is_small  = float(row["is_small"])
        # Use mask-derived label; fall back to CSV only when mask is empty (background slice)
        if mask_pixels > 0:
            is_small_val = 1.0 if mask_pixels < 200 else 0.0
        else:
            is_small_val = csv_is_small   # background slice — use CSV
        d["is_small"] = torch.tensor(is_small_val, dtype=torch.float32)
        d["fname"]    = fname
        return d

# ============================================================================
# 5. BUILD DATA LOADERS  (patient-wise 70/15/15 split)
# ============================================================================
print("\n🔄 Loading CSVs ...")
dfs = []
for i in range(5):
    p = DATA_DIR / f"client_{i}_iid.csv"
    if p.exists():
        df_i = pd.read_csv(p)
        dfs.append(df_i)
        print(f"  Client {i}: {len(df_i)} rows")
    else:
        print(f"  ⚠️  Missing {p}")

central_df = pd.concat(dfs, ignore_index=True)
print(f"\n✅ Combined: {len(central_df)} rows, "
      f"{central_df['patient_id'].nunique()} patients")

patients = central_df["patient_id"].unique()
train_p, tmp_p = train_test_split(patients, test_size=0.30, random_state=42)
val_p,  test_p = train_test_split(tmp_p,    test_size=0.50, random_state=42)

train_df = central_df[central_df["patient_id"].isin(train_p)].reset_index(drop=True)
val_df   = central_df[central_df["patient_id"].isin(val_p)].reset_index(drop=True)
test_df  = central_df[central_df["patient_id"].isin(test_p)].reset_index(drop=True)
print(f"Train {len(train_df)} | Val {len(val_df)} | Test {len(test_df)}")

NW = 4 if device.type == "cuda" else 0

def make_loaders(bs=BATCH_SIZE):
    tr = LIDCNoduleDataset(train_df, DATA_DIR, is_train=True,  augment_rare=True)
    va = LIDCNoduleDataset(val_df,   DATA_DIR, is_train=False, augment_rare=False)
    te = LIDCNoduleDataset(test_df,  DATA_DIR, is_train=False, augment_rare=False)
    trl = DataLoader(tr, batch_size=bs, shuffle=True,  num_workers=NW, pin_memory=True)
    val = DataLoader(va, batch_size=bs, shuffle=False, num_workers=NW, pin_memory=True)
    tel = DataLoader(te, batch_size=bs, shuffle=False, num_workers=NW, pin_memory=True)
    return trl, val, tel

train_loader, val_loader, test_loader = make_loaders()
print("✅ DataLoaders ready")

# ============================================================================
# 6. LOSS + METRICS
# ============================================================================

class CombinedLoss(nn.Module):
    """Dice-CE 0.7/0.3 — identical to your original."""
    def __init__(self):
        super().__init__()
        self.loss = DiceCELoss(
            sigmoid=True, softmax=False, include_background=False,
            to_onehot_y=False, lambda_dice=0.7, lambda_ce=0.3
        )
    def forward(self, pred, target): return self.loss(pred, target)


class FocalTverskyLoss(nn.Module):
    """
    Focal Tversky Loss — penalises FN more (alpha=0.7, beta=0.3, gamma=0.75).
    Works much better for small / rare nodules than vanilla Dice-CE.
    """
    def __init__(self, alpha=0.7, beta=0.3, gamma=0.75, smooth=1e-6):
        super().__init__()
        self.alpha = alpha   # weight on FN  (recall-boosting)
        self.beta  = beta    # weight on FP
        self.gamma = gamma   # focal exponent
        self.smooth = smooth

    def forward(self, logits, targets):
        probs  = torch.sigmoid(logits)
        tp     = (probs * targets).sum(dim=(2, 3))
        fp     = (probs * (1 - targets)).sum(dim=(2, 3))
        fn     = ((1 - probs) * targets).sum(dim=(2, 3))
        tversky = (tp + self.smooth) / (tp + self.alpha*fn + self.beta*fp + self.smooth)
        focal_tversky = (1 - tversky) ** self.gamma
        return focal_tversky.mean()


class HybridLoss(nn.Module):
    """0.5 * DiceCE + 0.5 * FocalTversky — best of both worlds."""
    def __init__(self):
        super().__init__()
        self.dice_ce = CombinedLoss()
        self.ft      = FocalTverskyLoss()

    def forward(self, pred, target):
        return 0.5 * self.dice_ce(pred, target) + 0.5 * self.ft(pred, target)


class RUSLoss(nn.Module):
    """Rare-Uncertainty-Sensitivity loss — unchanged from your code."""
    def __init__(self, weight=0.1, num_bins=10):
        super().__init__()
        self.weight   = weight
        self.num_bins = num_bins

    def compute_entropy(self, probs):
        return -torch.sum(probs * torch.log(probs + 1e-8), dim=1)

    def compute_ece(self, probs, targets):
        conf, preds = torch.max(probs, dim=1)
        tgt = (targets.squeeze(1) > 0.5).float()
        bins = torch.linspace(0, 1, self.num_bins + 1, device=probs.device)
        ece  = 0.0
        for i in range(self.num_bins):
            m = (conf.flatten() > bins[i]) & (conf.flatten() <= bins[i+1])
            if m.sum() > 0:
                acc  = (preds.flatten().float()[m] == tgt.flatten()[m]).float().mean()
                conf_mean = conf.flatten()[m].mean()
                ece += torch.abs(conf_mean - acc) * m.sum().float()
        return ece / (conf.flatten().numel() + 1e-8)

    def forward(self, probs, targets, is_small):
        entropy      = self.compute_entropy(probs)
        ece          = self.compute_ece(probs, targets)
        is_small_map = is_small.float().unsqueeze(1).unsqueeze(2).expand_as(entropy)
        return (is_small_map * entropy).mean() + ece * self.weight


def compute_metrics(preds, targets, threshold=0.5):
    pb = (torch.sigmoid(preds) > threshold).float()
    tb = (targets > 0.5).float()
    pf, tf = pb.view(-1), tb.view(-1)
    tp = (pf * tf).sum()
    fp = (pf * (1 - tf)).sum()
    fn = ((1 - pf) * tf).sum()
    tn = ((1 - pf) * (1 - tf)).sum()
    return {
        "dice":        ((2*tp + 1e-8) / (2*tp + fp + fn + 1e-8)).item(),
        "sensitivity": ((tp + 1e-8)   / (tp + fn + 1e-8)).item(),
        "specificity": ((tn + 1e-8)   / (tn + fp + 1e-8)).item(),
        "precision":   ((tp + 1e-8)   / (tp + fp + 1e-8)).item(),
        "iou":         ((tp + 1e-8)   / (tp + fp + fn + 1e-8)).item(),
    }

# ============================================================================
# 7. MODEL DEFINITIONS
# ============================================================================

class Model1_UNet(nn.Module):
    """
    EXACT same architecture as the original checkpoint:
      channels=(32,64,128,256,512), strides=(2,2,2,2),
      num_res_units=2, norm=BatchNorm, dropout=0.1
    Architecture MUST NOT change — we are resuming from the saved weights.
    Optimisation comes from: HybridLoss, ReduceLROnPlateau, deeper augmentation, TTA.
    """
    def __init__(self):
        super().__init__()
        self.unet = UNet(
            spatial_dims=2, in_channels=1, out_channels=1,
            channels=(32, 64, 128, 256, 512),   # ← original, DO NOT change
            strides=(2, 2, 2, 2),
            num_res_units=2,                     # ← original, DO NOT change
            norm=Norm.BATCH,                     # ← original BatchNorm
            dropout=0.1,
        )
    def forward(self, x): return self.unet(x)


class Model3_SwinUNet(nn.Module):
    """
    SwinUNETR — EXACT original architecture to allow full checkpoint resume:
      feature_size=24, depths=(2,2,2,2), num_heads=(3,6,12,24), norm=batch.
    Architecture MUST match the checkpoint. Optimisation comes from:
    HybridLoss, deeper augmentation, ReduceLROnPlateau, TTA.
    After this run hits the target or patience, a fresh feature_size=48
    model can be trained from scratch in a separate session if needed.
    """
    def __init__(self, feature_size=24):
        super().__init__()
        self.swinunetr = SwinUNETR(
            spatial_dims=2,
            in_channels=1,
            out_channels=1,
            feature_size=feature_size,   # ← 24 = original checkpoint arch
            depths=(2, 2, 2, 2),         # ← original
            num_heads=(3, 6, 12, 24),    # ← original
            norm_name="batch",           # ← original
            dropout_path_rate=0.1,       # ← original
        )
    def forward(self, x): return self.swinunetr(x)

# ============================================================================
# 8. TTA (Test-Time Augmentation)  —  4 deterministic flips/rots
# ============================================================================

def tta_predict(model, images):
    """Average predictions over 4 TTA variants."""
    augs = [
        lambda x: x,
        lambda x: torch.flip(x, [3]),
        lambda x: torch.flip(x, [2]),
        lambda x: torch.rot90(x, k=1, dims=[2, 3]),
    ]
    de_augs = [
        lambda x: x,
        lambda x: torch.flip(x, [3]),
        lambda x: torch.flip(x, [2]),
        lambda x: torch.rot90(x, k=-1, dims=[2, 3]),
    ]
    preds = []
    with torch.no_grad():
        for aug, de_aug in zip(augs, de_augs):
            out = model(aug(images))
            preds.append(de_aug(out))
    return torch.mean(torch.stack(preds, dim=0), dim=0)

# ============================================================================
# 9. TRAIN / VALIDATE EPOCH  (AMP + RUS)
# ============================================================================

def train_epoch(model, loader, optimizer, seg_loss, rus_loss_fn,
                scaler, rus_weight, epoch):
    model.train()
    tot_loss = tot_dice = 0.0
    n = 0
    for batch in tqdm(loader, desc=f"  Train {epoch}", leave=False):
        imgs     = batch["image"].to(device)
        masks    = batch["mask"].to(device)
        is_small = batch["is_small"].to(device)
        optimizer.zero_grad()
        with autocast():
            logits   = model(imgs)
            loss_seg = seg_loss(logits, masks)
            loss_rus = torch.tensor(0.0, device=device)
            if rus_weight > 0:
                p      = torch.sigmoid(logits)
                probs  = torch.softmax(torch.cat([1-p, p], dim=1), dim=1)
                loss_rus = rus_loss_fn(probs, masks, is_small) * rus_weight
            loss = loss_seg + loss_rus
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        m         = compute_metrics(logits.detach(), masks)
        tot_loss += loss.item()
        tot_dice += m["dice"]
        n        += 1
    return {"loss": tot_loss/n, "dice": tot_dice/n}


def validate_epoch(model, loader, seg_loss, rus_loss_fn, rus_weight, epoch):
    model.eval()
    tot_loss = tot_dice = tot_rare = 0.0
    n = rare_n = 0
    with torch.no_grad():
        for batch in tqdm(loader, desc=f"  Val   {epoch}", leave=False):
            imgs     = batch["image"].to(device)
            masks    = batch["mask"].to(device)
            is_small = batch["is_small"].to(device)
            with autocast():
                logits   = tta_predict(model, imgs)
                loss_seg = seg_loss(logits, masks)
                loss_rus = torch.tensor(0.0, device=device)
                if rus_weight > 0:
                    p      = torch.sigmoid(logits)
                    probs  = torch.softmax(torch.cat([1-p, p], dim=1), dim=1)
                    loss_rus = rus_loss_fn(probs, masks, is_small) * rus_weight
                loss = loss_seg + loss_rus
            m         = compute_metrics(logits, masks)
            tot_loss += loss.item()
            tot_dice += m["dice"]
            n        += 1
            rare_idx  = (is_small > 0.5).nonzero(as_tuple=True)[0]
            if len(rare_idx) > 0:
                # Compute per-sample rare dice and accumulate sum + count
                for ri in rare_idx:
                    rm = compute_metrics(
                        logits[ri:ri+1], masks[ri:ri+1]
                    )
                    tot_rare += rm["dice"]
                    rare_n   += 1
    rare_dice = tot_rare / rare_n if rare_n > 0 else 0.0
    return {"loss": tot_loss/n, "dice": tot_dice/n, "rare_dice": rare_dice,
            "n_rare_samples": rare_n}

# ============================================================================
# 10. UNIVERSAL RESUME-AWARE TRAINING LOOP
# ============================================================================

def run_training(
    model_class,
    model_name,
    train_loader,
    val_loader,
    seg_loss_class,       # e.g. HybridLoss  or  CombinedLoss
    rus_weight   = 0.1,
    max_epochs   = 200,
    patience     = 30,
    init_lr      = 1e-4,
    weight_decay = 1e-5,
    model_kwargs = None,
    dice_target  = None,   # optional early-exit when target reached
):
    """
    Fully self-contained trainer.
    - Loads latest checkpoint if it exists.
    - Saves checkpoint every epoch, best model when composite score improves.
    - Returns (model, history).
    """
    if model_kwargs is None: model_kwargs = {}

    model = model_class(**model_kwargs).to(device)
    ckpt_path    = MODEL_DIR / f"{model_name}_checkpoint.pth"
    best_path    = MODEL_DIR / f"{model_name}_best.pth"
    history_path = MODEL_DIR / f"{model_name}_history.json"

    # ---- history schema -------------------------------------------------
    hist_keys = ["epochs", "train_loss", "train_dice",
                 "val_dice", "val_rare_dice", "composite", "lr"]
    history   = {k: [] for k in hist_keys}

    start_epoch    = 1
    best_composite = 0.0
    es_counter     = 0

    # ---- load checkpoint ------------------------------------------------
    if ckpt_path.exists():
        print(f"\n🔄 Found checkpoint: {ckpt_path}")
        ckpt     = torch.load(ckpt_path, map_location=device)
        saved_sd = ckpt["model_state_dict"]
        model_sd = model.state_dict()

        # Detect architecture mismatches (different channels/res_units/norm)
        missing    = [k for k in model_sd if k not in saved_sd]
        unexpected = [k for k in saved_sd if k not in model_sd]
        mismatched = [k for k in model_sd if k in saved_sd
                      and saved_sd[k].shape != model_sd[k].shape]

        if missing or unexpected or mismatched:
            print(f"   ⚠️  Architecture mismatch — cannot do full resume:")
            print(f"      Missing keys    : {len(missing)}")
            print(f"      Unexpected keys : {len(unexpected)}")
            print(f"      Shape mismatches: {len(mismatched)}")
            # strict=False still crashes on shape mismatches in PyTorch.
            # Manually keep only keys that exist in both AND have matching shapes.
            compatible_sd = {
                k: v for k, v in saved_sd.items()
                if k in model_sd and v.shape == model_sd[k].shape
            }
            model_sd.update(compatible_sd)
            model.load_state_dict(model_sd, strict=True)
            print(f"   ✅ Transferred {len(compatible_sd)}/{len(model_sd)} compatible weight tensors")
            print(f"   ▸ Epoch counter reset to 1 (architecture change — fresh training from partial weights)")
            # Don't restore epoch or best_composite — incompatible arch means we retrain
        else:
            print(f"   ✅ Architecture matches — full resume")
            model.load_state_dict(saved_sd, strict=True)
            start_epoch    = ckpt.get("epoch", 0) + 1
            best_composite = ckpt.get("best_composite",
                             ckpt.get("best_dice",
                             ckpt.get("best_composite_score", 0.0)))
            # If checkpoint has 0.0 (old training didn't save composite),
            # try to read it from the best.pth which was saved with val_dice
            if best_composite == 0.0 and best_path.exists():
                try:
                    best_ckpt = torch.load(best_path, map_location="cpu")
                    best_composite = best_ckpt.get("composite",
                                    best_ckpt.get("dice",
                                    best_ckpt.get("best_dice", 0.0)))
                    print(f"   ▸ best_composite recovered from best.pth: {best_composite:.4f}")
                except Exception:
                    pass

        if history_path.exists():
            try:
                with open(history_path) as f:
                    loaded = json.load(f)
                # Ensure every required key exists and is a list (not scalar)
                for k in hist_keys:
                    v = loaded.get(k, [])
                    history[k] = list(v) if isinstance(v, (list, tuple)) else []
            except Exception:
                history = {k: [] for k in hist_keys}

        print(f"   ▸ Start epoch          : {start_epoch}")
        print(f"   ▸ Best composite so far: {best_composite:.4f}")
        print(f"   ▸ History epochs loaded: {len(history.get('val_dice', []))}")
    else:
        print(f"\n🆕 Fresh training: {model_name}")

    # ---- init optimiser / scheduler / scaler ----------------------------
    seg_loss    = seg_loss_class()
    rus_loss_fn = RUSLoss(weight=rus_weight)
    optimizer   = AdamW(model.parameters(), lr=init_lr,
                        weight_decay=weight_decay)
    scheduler   = ReduceLROnPlateau(optimizer, mode="max", factor=0.5,
                                    patience=12, verbose=True, min_lr=1e-7)
    scaler      = GradScaler()

    # Only restore optimizer/scheduler when architecture fully matched
    if ckpt_path.exists() and start_epoch > 1:
        # Try to restore optimizer momentum/adam states for warm resume
        try:
            optimizer.load_state_dict(ckpt["optimizer_state_dict"])
            print("   ▸ Optimizer restored ✅")
        except Exception as e:
            # Old checkpoints may have incompatible param group structure.
            # Extract the last saved LR and apply it directly so we don't
            # start cold at init_lr=1e-4 but continue from where training stopped.
            try:
                saved_lr = ckpt["optimizer_state_dict"]["param_groups"][0]["lr"]
            except Exception:
                saved_lr = init_lr
            for pg in optimizer.param_groups:
                pg["lr"] = saved_lr
            print(f"   ⚠️  Optimizer state incompatible ({e})")
            print(f"   ▸ Fresh optimizer with saved LR={saved_lr:.2e} (adam states reset)")

        # Never restore ReduceLROnPlateau state — its internal "best" would poison
        # the scheduler into thinking every epoch is worse than the old best.
        current_lr = optimizer.param_groups[0]["lr"]
        print(f"   ▸ Scheduler reset to fresh state (LR={current_lr:.2e} from optimizer)")
    elif ckpt_path.exists() and start_epoch == 1:
        print("   ▸ Fresh optimizer/scheduler (architecture mismatch or new run)")

    # ---- training loop --------------------------------------------------
    print("=" * 70)
    print(f"🚀 {model_name}  |  Epochs {start_epoch}–{max_epochs}  "
          f"|  patience={patience}  |  bs={BATCH_SIZE}  |  AMP+TTA")
    print(f"   Params: {sum(p.numel() for p in model.parameters()):,}")
    print(f"   Loss  : {seg_loss_class.__name__}  +  RUSLoss(w={rus_weight})")
    if dice_target:
        print(f"   Target: Dice ≥ {dice_target:.2f}")
    print("=" * 70)

    for epoch in range(start_epoch, max_epochs + 1):
        print(f"\n📅 [{model_name}] Epoch {epoch}/{max_epochs}")

        tr = train_epoch(model, train_loader, optimizer, seg_loss,
                         rus_loss_fn, scaler, rus_weight, epoch)
        va = validate_epoch(model, val_loader, seg_loss,
                            rus_loss_fn, rus_weight, epoch)

        composite = 0.7 * va["rare_dice"] + 0.3 * va["dice"]
        lr_now    = optimizer.param_groups[0]["lr"]
        scheduler.step(composite)

        n_rare = va.get("n_rare_samples", 0)
        print(f"   Train  → loss={tr['loss']:.4f}  dice={tr['dice']:.4f}")
        print(f"   Val    → dice={va['dice']:.4f}  rare={va['rare_dice']:.4f}"
              f"  comp={composite:.4f}  lr={lr_now:.2e}  [rare_samples={n_rare}]")

        # update history
        history["epochs"].append(epoch)
        history["train_loss"].append(tr["loss"])
        history["train_dice"].append(tr["dice"])
        history["val_dice"].append(va["dice"])
        history["val_rare_dice"].append(va["rare_dice"])
        history["composite"].append(composite)
        history["lr"].append(lr_now)

        # save best
        if composite > best_composite:
            best_composite = composite
            es_counter     = 0
            torch.save({
                "epoch": epoch, "model_state_dict": model.state_dict(),
                "composite": best_composite, "val_dice": va["dice"],
                "val_rare_dice": va["rare_dice"],
            }, best_path)
            print(f"   ⭐ NEW BEST composite={best_composite:.4f}  saved → {best_path.name}")
        else:
            es_counter += 1
            print(f"   ❗ No improvement ({es_counter}/{patience})")
            if es_counter >= patience:
                print(f"   🛑 Early stop at epoch {epoch}")
                break

        # save checkpoint
        torch.save({
            "epoch":              epoch,
            "model_state_dict":   model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "scheduler_state_dict": scheduler.state_dict(),
            "best_composite":     best_composite,
        }, ckpt_path)
        with open(history_path, "w") as f:
            json.dump(history, f, indent=2)

        # target reached?
        if dice_target and va["dice"] >= dice_target:
            print(f"\n🎯 TARGET REACHED: Dice={va['dice']:.4f} ≥ {dice_target:.2f}")
            break

    print(f"\n✅ {model_name} DONE  |  Best composite={best_composite:.4f}")
    return model, history

# ============================================================================
# 11A. TASK 1 — OPTIMISE MODEL 1 (U-Net)
#      Current Dice ≈ 0.82  →  target ≥ 0.87
#      Changes vs original:
#        • Wider channels (64-512 vs 32-512) + 3 residual units
#        • Instance Norm (better for small structures)
#        • HybridLoss (DiceCE + FocalTversky) ← key upgrade
#        • RUS weight = 0.15  (was 0.1)
#        • ReduceLROnPlateau  (was CosineAnnealing — plateau-aware)
#        • Deeper augmentation (zoom, smooth)
#        • TTA at validation
#        • Resume-aware: picks up from step4.1_unet_checkpoint.pth
# ============================================================================
print("\n" + "="*70)
print("TASK 1 — OPTIMISING MODEL 1: U-Net  (target Dice ≥ 0.87)")
print("="*70)

m1_model, m1_hist = run_training(
    model_class     = Model1_UNet,
    model_name      = "step4.1_unet",       # ← exact checkpoint name
    train_loader    = train_loader,
    val_loader      = val_loader,
    seg_loss_class  = HybridLoss,            # key upgrade: FocalTversky
    rus_weight      = 0.15,                  # slightly higher RUS penalty
    max_epochs      = 200,
    patience        = 30,
    init_lr         = 1e-4,                  # restored from optimizer state (scheduler reset to fresh)
    weight_decay    = 1e-5,
    dice_target     = 0.87,
)

# ============================================================================
# 11B. TASK 2 — MODEL 3: SwinUNETR  (target Dice ≥ 0.90)
#      Changes vs original:
#        • feature_size=48 (was 24) — double capacity
#        • deeper middle: depths=(2,2,4,2)
#        • Instance norm (was batch)
#        • HybridLoss
#        • RUS weight = 0.1
#        • ReduceLROnPlateau
#        • TTA at validation
#        • Resume-aware: picks up from step4.3_swinunet_checkpoint.pth
#
#  NOTE: SwinUNETR with feature_size=48 needs ~13-16 GB VRAM.
#        On T4 (16 GB) batch_size will be set to 16 automatically.
#        On A100 (40 GB) batch_size will be 48.
# ============================================================================
print("\n" + "="*70)
print("TASK 2 — MODEL 3: SwinUNETR  (target Dice ≥ 0.90)")
print("="*70)

# SwinUNETR feature_size=24 is lightweight — reuse existing loaders on all GPUs.
# (Only a feature_size=48 model would need batch reduction on T4.)
swin_train_loader = train_loader
swin_val_loader   = val_loader
print(f"  ✅ SwinUNETR using batch_size={BATCH_SIZE} (feature_size=24, fits all GPUs)")

m3_model, m3_hist = run_training(
    model_class     = Model3_SwinUNet,
    model_name      = "step4.3_swinunet",   # ← exact checkpoint name
    train_loader    = swin_train_loader,
    val_loader      = swin_val_loader,
    seg_loss_class  = HybridLoss,
    rus_weight      = 0.10,
    max_epochs      = 250,
    patience        = 35,
    init_lr         = 1e-4,                  # fresh / low if resuming
    weight_decay    = 1e-5,
    model_kwargs    = {"feature_size": 24},  # match checkpoint arch
    dice_target     = 0.90,
)

# ============================================================================
# 12. FINAL EVALUATION ON TEST SET
# ============================================================================
print("\n" + "="*70)
print("FINAL TEST SET EVALUATION")
print("="*70)

def evaluate_model(model, model_name, loader):
    """Load best checkpoint and evaluate on test loader with TTA."""
    best_path = MODEL_DIR / f"{model_name}_best.pth"
    if best_path.exists():
        ckpt = torch.load(best_path, map_location=device)
        model.load_state_dict(ckpt["model_state_dict"])
        print(f"  ✅ Loaded best checkpoint: epoch={ckpt.get('epoch','?')} "
              f"composite={ckpt.get('composite', 0):.4f}")
    else:
        print(f"  ⚠️  No best checkpoint found for {model_name}, using current weights")

    model.eval()
    all_metrics = []
    with torch.no_grad():
        for batch in tqdm(loader, desc=f"  Test {model_name}", leave=False):
            imgs  = batch["image"].to(device)
            masks = batch["mask"].to(device)
            with autocast():
                logits = tta_predict(model, imgs)
            m = compute_metrics(logits, masks)
            all_metrics.append(m)

    avg = {k: np.mean([m[k] for m in all_metrics]) for k in all_metrics[0]}
    print(f"\n  🧪 TEST RESULTS — {model_name}")
    for k, v in avg.items():
        print(f"     {k:14s}: {v:.4f}")
    return avg

print("\n--- Model 1: U-Net ---")
m1_test = evaluate_model(m1_model, "step4.1_unet", test_loader)

print("\n--- Model 3: SwinUNETR ---")
m3_model_eval = Model3_SwinUNet(feature_size=24).to(device)
m3_test = evaluate_model(m3_model_eval, "step4.3_swinunet", test_loader)

# ============================================================================
# 13. SUMMARY TABLE
# ============================================================================
print("\n" + "="*70)
print("SUMMARY")
print("="*70)
summary = pd.DataFrame({
    "Model":       ["Model1 U-Net (optimised)", "Model3 SwinUNETR (90+ target)"],
    "Test Dice":   [m1_test["dice"],  m3_test["dice"]],
    "Sensitivity": [m1_test["sensitivity"], m3_test["sensitivity"]],
    "Precision":   [m1_test["precision"],   m3_test["precision"]],
    "IoU":         [m1_test["iou"],         m3_test["iou"]],
    "Val Best Dice (M1)": [max(m1_hist.get("val_dice", [0])), "-"],
    "Val Best Dice (M3)": ["-", max(m3_hist.get("val_dice", [0]))],
})
print(summary.to_string(index=False))

summary.to_csv(MODEL_DIR / "step6_final_summary.csv", index=False)
print(f"\n📁 Summary saved → {MODEL_DIR / 'step6_final_summary.csv'}")
print("\n🎉 STEP 6 COMPLETE!")
print("   Checkpoints : step4.1_unet_checkpoint.pth | step4.3_swinunet_checkpoint.pth")
print("   Best models : step4.1_unet_best.pth        | step4.3_swinunet_best.pth")
print("   Histories   : step4.1_unet_history.json    | step4.3_swinunet_history.json")