# -*- coding: utf-8 -*-
"""steps7_to_10_fl_experiments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1scrrSAv-85OiCAmZl9Cppd3apyJKae8f
"""

# -*- coding: utf-8 -*-
"""
=============================================================================
  STEPS 7–10  |  FEDERATED LEARNING COMPLETE IMPLEMENTATION
  RareNoduleFL — LIDC-IDRI  |  U-Net FedAvg on A100

  Step 7  — Flower NoduleClient (fully implemented per project spec)
  Step 8  — FL Experiment 1 : IID FedAvg (20 rounds, 5 clients)
  Step 9  — FL Experiment 2 : Non-IID + Heterogeneous noise + RUS loss
  Step 10 — Ablation study  : RUS on vs off + McNemar + paired t-test

  PROCESSOR  : A100 (required — 5 sequential client models need 40 GB VRAM)
  MODEL      : U-Net warm-started from step4.1_unet_best.pth (Dice=0.8445)
  RESUME     : Every round checkpointed — re-run to continue from last round.

  DRIVE OUTPUTS:
    models/  fl_iid_global_{checkpoint,best,history,client_metrics}.*
             fl_noniid_rus_global_*.*
             fl_noniid_norus_global_*.*
    results/ fl_learning_curves.png      Paper Figure 3
             fl_client_drift.png         Paper Figure 3b
             fl_heterogeneity_bars.png   Paper Figure 6
             fl_ece_comparison.png       Paper Figure 4
             fl_ablation_table.csv       Paper Table 2
             fl_statistical_tests.txt    McNemar + paired t-test
=============================================================================
"""

# ============================================================================
# 0. INSTALL
# ============================================================================
print("📦 Installing dependencies ...")
import subprocess, sys

subprocess.run([sys.executable, "-m", "pip", "install",
    "torch==2.6.0", "torchvision==0.21.0", "torchaudio==2.6.0",
    "--index-url", "https://download.pytorch.org/whl/cu121", "-q"], check=False)
subprocess.run([sys.executable, "-m", "pip", "install",
    "monai==1.5.0", "flwr==1.7.0",
    "numpy==1.26.4", "pandas==2.2.0",
    "scikit-learn==1.4.0", "scipy",
    "matplotlib", "tqdm", "-q"], check=False)
print("✅ Done. Restart runtime once if import errors appear.")

# ============================================================================
# 1. MOUNT + PATHS
# ============================================================================
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from pathlib import Path
BASE_DIR    = Path("/content/drive/MyDrive/Rare Lung Nodules")
DATA_DIR    = BASE_DIR / "preprocessed_lidc"
MODEL_DIR   = BASE_DIR / "models"
RESULTS_DIR = BASE_DIR / "results"
MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
print(f"✅ BASE:{BASE_DIR} | DATA:{DATA_DIR} | MODELS:{MODEL_DIR}")

# ============================================================================
# 2. IMPORTS
# ============================================================================
import torch, json, warnings, copy
import numpy as np, pandas as pd
import torch.nn as nn
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import flwr as fl

from typing           import Dict, List, Optional, Tuple
from collections      import defaultdict
from torch.utils.data import Dataset, DataLoader
from torch.optim      import AdamW
from torch.cuda.amp   import autocast, GradScaler
from sklearn.model_selection import train_test_split
from scipy            import stats as scipy_stats
from tqdm             import tqdm

from monai.networks.nets   import UNet
from monai.networks.layers import Norm
from monai.losses          import DiceCELoss
from monai.transforms import (
    Compose, RandFlipd, RandRotate90d, RandAffined,
    RandAdjustContrastd, RandGaussianNoised,
    ToTensord, ScaleIntensityd,
)

warnings.filterwarnings("ignore")

device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
gpu_mem = torch.cuda.get_device_properties(0).total_memory/1e9 \
          if device.type == "cuda" else 0
FL_BATCH   = 16 if gpu_mem < 30 else 32
EVAL_BATCH = FL_BATCH * 2
print(f"\n✅ {device}  GPU:{torch.cuda.get_device_name(0) if device.type=='cuda' else 'CPU'}"
      f"  ({gpu_mem:.1f}GB)  FL_batch={FL_BATCH}")

# ============================================================================
# 3. DATASET
# ============================================================================
SMALL_PIX = 200   # mask pixels < 200 ≈ nodule < ~10 mm

class LIDCNoduleDataset(Dataset):
    def __init__(self, data_df, data_dir, is_train=True,
                 augment_rare=False, client_noise_sigma=15.0):
        self.data_dir = Path(data_dir)
        self.sigma    = client_noise_sigma
        if augment_rare and is_train:
            rare     = data_df[data_df["is_small"] == 1]
            data_df  = pd.concat([data_df, rare, rare], ignore_index=True)
        self.data_df  = data_df.reset_index(drop=True)
        self.tfm      = self._tfm(is_train)

    def _tfm(self, is_train):
        # ResizeWithPadOrCropd ensures ALL slices → 256x256 regardless of
        # original NPY size. Some older preprocessed files are 128x128.
        # This prevents the collation crash: "stack expects equal size".
        from monai.transforms import ResizeWithPadOrCropd
        base = [ResizeWithPadOrCropd(keys=["image","mask"],
                                     spatial_size=[256,256],
                                     mode="constant")]
        if is_train:
            return Compose(base + [
                RandFlipd(["image","mask"], prob=0.5, spatial_axis=0),
                RandFlipd(["image","mask"], prob=0.5, spatial_axis=1),
                RandRotate90d(["image","mask"], prob=0.5, max_k=3),
                RandAffined(["image","mask"], prob=0.5,
                            rotate_range=(np.pi/18,np.pi/18),
                            scale_range=(0.1,0.1),
                            mode=["bilinear","nearest"],
                            padding_mode="border"),
                RandGaussianNoised(["image"], prob=0.5,
                                   mean=0.0, std=self.sigma/255.0),
                RandAdjustContrastd(["image"], prob=0.5, gamma=(0.85,1.15)),
                ScaleIntensityd(["image"], minv=0.0, maxv=1.0),
                ToTensord(["image","mask"]),
            ])
        return Compose(base + [
            ScaleIntensityd(["image"],minv=0.0,maxv=1.0),
            ToTensord(["image","mask"])
        ])

    def __len__(self): return len(self.data_df)

    def __getitem__(self, idx):
        row   = self.data_df.iloc[idx]
        fname = row["fname"]
        try:
            image = np.load(self.data_dir/f"{fname}_img.npy").astype(np.float32)
            mask  = np.load(self.data_dir/f"{fname}_mask.npy").astype(np.float32)
        except Exception as e:
            print(f"⚠️ {fname}: {e}")
            image = np.zeros((1,256,256),np.float32)
            mask  = np.zeros((1,256,256),np.float32)
        d = self.tfm({"image":image,"mask":mask})
        # Derive is_small from mask pixels — NOT the broken CSV column
        mp = float((mask > 0.5).sum())
        d["is_small"] = torch.tensor(1.0 if 0<mp<SMALL_PIX else 0.0,
                                      dtype=torch.float32)
        d["label"]    = torch.tensor(row["label"], dtype=torch.long)
        d["fname"]    = fname
        return d

# ============================================================================
# 4. LOAD DATA + BUILD SPLITS
# ============================================================================
print("\n🔄 Loading CSVs ...")
iid_client_dfs = []
for i in range(5):
    p = DATA_DIR / f"client_{i}_iid.csv"
    if not p.exists():
        raise FileNotFoundError(f"{p} missing — run Steps 2/3 first")
    iid_client_dfs.append(pd.read_csv(p))
    print(f"  IID Client {i}: {len(iid_client_dfs[-1])} rows")

# Test set
test_csv = DATA_DIR / "test_iid.csv"
if test_csv.exists():
    test_df = pd.read_csv(test_csv)
    print(f"  Test (test_iid.csv): {len(test_df)} rows")
else:
    all_df = pd.concat(iid_client_dfs, ignore_index=True)
    pats   = all_df["patient_id"].unique()
    _, tp  = train_test_split(pats, test_size=0.15, random_state=42)
    test_df = all_df[all_df["patient_id"].isin(tp)].reset_index(drop=True)
    iid_client_dfs = [df[~df["patient_id"].isin(tp)].reset_index(drop=True)
                      for df in iid_client_dfs]
    print(f"  Test (carved): {len(test_df)} rows")

# Non-IID: sort by patient+nodule ID as size proxy, split into quintiles
print("\n🔄 Building Non-IID splits ...")
all_train = pd.concat(iid_client_dfs, ignore_index=True).sample(
    frac=1, random_state=42).reset_index(drop=True)
all_train["size_rank"] = (
    all_train["patient_id"].str.extract(r"(\d+)")[0].astype(int)*100
    + all_train["nodule_id"].str.extract(r"(\d+)")[0].fillna(0).astype(int)
)
sorted_train = all_train.sort_values("size_rank").reset_index(drop=True)
quintiles    = np.array_split(sorted_train, 5)
SMALL_Q = pd.concat(quintiles[:2], ignore_index=True)
LARGE_Q = pd.concat(quintiles[3:], ignore_index=True)

small_ratios = [0.80, 0.65, 0.50, 0.35, 0.20]
noniid_client_dfs = []
n_per = len(sorted_train) // 5
for i, ratio in enumerate(small_ratios):
    ns = int(n_per*ratio); nl = n_per-ns
    ss = i*(len(SMALL_Q)//5); ls = i*(len(LARGE_Q)//5)
    cdf = pd.concat([SMALL_Q.iloc[ss:ss+ns],
                     LARGE_Q.iloc[ls:ls+nl]],
                    ignore_index=True).sample(frac=1,random_state=100+i)
    noniid_client_dfs.append(cdf.reset_index(drop=True))
    print(f"  Non-IID Client {i}: {len(cdf)} rows  ({ratio*100:.0f}% small-Q)")

CLIENT_NOISE_SIGMAS = [5, 10, 15, 20, 25]

def build_client_loaders(client_dfs, noise_sigmas=None, augment_rare=True):
    loaders = []
    for i, df in enumerate(client_dfs):
        sigma = noise_sigmas[i] if noise_sigmas else 15.0
        ds    = LIDCNoduleDataset(df, DATA_DIR, is_train=True,
                                   augment_rare=augment_rare,
                                   client_noise_sigma=sigma)
        loaders.append(DataLoader(ds, batch_size=FL_BATCH, shuffle=True,
                                   num_workers=2, pin_memory=True,
                                   drop_last=True))
    return loaders

test_ds     = LIDCNoduleDataset(test_df, DATA_DIR, is_train=False)
test_loader = DataLoader(test_ds, batch_size=EVAL_BATCH, shuffle=False,
                          num_workers=2, pin_memory=True)
print(f"\n✅ Test loader: {len(test_df)} samples")

# ============================================================================
# 5. MODEL
# ============================================================================
class UNetModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.unet = UNet(spatial_dims=2, in_channels=1, out_channels=1,
                         channels=(32,64,128,256,512), strides=(2,2,2,2),
                         num_res_units=2, norm=Norm.BATCH, dropout=0.1)
    def forward(self, x): return self.unet(x)

def load_pretrained_unet(verbose=True):
    model = UNetModel().to(device)
    p     = MODEL_DIR / "step4.1_unet_best.pth"
    if p.exists():
        ckpt = torch.load(p, map_location=device)
        model.load_state_dict(ckpt["model_state_dict"])
        if verbose:
            ep  = ckpt.get("epoch","?")
            dc  = ckpt.get("metrics",{}).get("dice", ckpt.get("dice","?"))
            print(f"  ✅ Warm-start from step4.1_unet_best.pth  (ep={ep}, dice={dc})")
    else:
        if verbose: print("  ⚠️  step4.1_unet_best.pth not found — random init")
    return model

# ============================================================================
# 6. LOSS + METRICS
# ============================================================================
class CombinedLoss(nn.Module):
    def __init__(self):
        super().__init__()
        self._l = DiceCELoss(sigmoid=True, include_background=False,
                              to_onehot_y=False, lambda_dice=0.7, lambda_ce=0.3)
    def forward(self, p, t): return self._l(p, t)

class RUSLoss(nn.Module):
    def __init__(self, weight=0.1, num_bins=10):
        super().__init__()
        self.w = weight; self.nb = num_bins
    def _entropy(self, probs):
        return -torch.sum(probs*torch.log(probs+1e-8), dim=1)
    def _ece(self, probs, targets):
        conf,preds = torch.max(probs, dim=1)
        tgt  = (targets.squeeze(1)>0.5).float()
        bins = torch.linspace(0,1,self.nb+1, device=probs.device)
        ece  = torch.tensor(0.0, device=probs.device)
        for i in range(self.nb):
            m = (conf.flatten()>bins[i])&(conf.flatten()<=bins[i+1])
            if m.sum()>0:
                acc = (preds.flatten().float()[m]==tgt.flatten()[m]).float().mean()
                ece += torch.abs(conf.flatten()[m].mean()-acc)*m.sum().float()
        return ece/(conf.flatten().numel()+1e-8)
    def forward(self, probs, targets, is_small):
        ent  = self._entropy(probs)
        ece  = self._ece(probs, targets)
        mask = is_small.float().unsqueeze(1).unsqueeze(2).expand_as(ent)
        return (mask*ent).mean() + ece*self.w

def compute_metrics(preds, targets, thr=0.5):
    pb=(torch.sigmoid(preds)>thr).float(); tb=(targets>0.5).float()
    pf,tf=pb.view(-1),tb.view(-1)
    tp=(pf*tf).sum(); fp=(pf*(1-tf)).sum()
    fn=((1-pf)*tf).sum(); tn=((1-pf)*(1-tf)).sum()
    return {"dice":    ((2*tp+1e-8)/(2*tp+fp+fn+1e-8)).item(),
            "sensitivity":((tp+1e-8)/(tp+fn+1e-8)).item(),
            "specificity":((tn+1e-8)/(tn+fp+1e-8)).item(),
            "precision":  ((tp+1e-8)/(tp+fp+1e-8)).item(),
            "iou":        ((tp+1e-8)/(tp+fp+fn+1e-8)).item()}

def compute_ece_scalar(model, loader):
    model.eval(); ca,aa=[],[]
    with torch.no_grad():
        for batch in loader:
            imgs=batch["image"].to(device); masks=batch["mask"].to(device)
            with autocast(): logits=model(imgs)
            ca.extend(torch.sigmoid(logits).view(-1).cpu().numpy().tolist())
            aa.extend((masks>0.5).float().view(-1).cpu().numpy().tolist())
    c=np.array(ca); a=np.array(aa); ece=0.0
    for i in range(10):
        m=(c>=i/10)&(c<(i+1)/10)
        if m.sum()>0: ece+=abs(c[m].mean()-a[m].mean())*m.sum()
    return float(ece/(len(c)+1e-8))

def collect_predictions(model, loader):
    model.eval(); ps,ts=[],[]
    with torch.no_grad():
        for batch in loader:
            imgs=batch["image"].to(device); masks=batch["mask"].to(device)
            with autocast(): logits=model(imgs)
            ps.extend((torch.sigmoid(logits)>0.5).float().view(-1).cpu().numpy().tolist())
            ts.extend((masks>0.5).float().view(-1).cpu().numpy().tolist())
    return np.array(ps), np.array(ts)

def dice_per_batch(model, loader):
    model.eval(); dices=[]
    with torch.no_grad():
        for batch in loader:
            imgs=batch["image"].to(device); masks=batch["mask"].to(device)
            with autocast(): logits=model(imgs)
            dices.append(compute_metrics(logits,masks)["dice"])
    return dices

# ============================================================================
# 7. STEP 7 — FLOWER NoduleClient (complete implementation)
# ============================================================================
class NoduleClient(fl.client.NumPyClient):
    """
    Flower federated learning client — LIDC-IDRI nodule segmentation.
    Implements get_parameters / fit / evaluate per Flower spec.
    Used in simulated FL: clients run sequentially on one GPU.
    """
    def __init__(self, cid, trainloader, valloader,
                 use_rus=False, n_local_epochs=2):
        self.cid            = cid
        self.trainloader    = trainloader
        self.valloader      = valloader
        self.use_rus        = use_rus
        self.n_local_epochs = n_local_epochs
        self.model          = UNetModel().to(device)
        self.seg_loss       = CombinedLoss()
        self.rus_loss_fn    = RUSLoss(weight=0.1)

    def get_parameters(self, config):
        return [v.cpu().numpy() for v in self.model.state_dict().values()]

    def set_parameters(self, parameters):
        keys = list(self.model.state_dict().keys())
        sd   = {k: torch.tensor(v) for k,v in zip(keys, parameters)}
        self.model.load_state_dict(sd, strict=True)

    def fit(self, parameters, config):
        self.set_parameters(parameters)
        self.model.train()
        optimizer = AdamW(self.model.parameters(), lr=1e-4, weight_decay=1e-5)
        scaler    = GradScaler()
        ep_dices, ep_losses = [], []
        for ep in range(self.n_local_epochs):
            tot_loss=tot_dice=0.0; n=0
            loader_iter = tqdm(self.trainloader,
                               desc=f"    C{self.cid} ep{ep+1}/{self.n_local_epochs}",
                               leave=False, ncols=80)
            for batch in loader_iter:
                imgs=batch["image"].to(device)
                masks=batch["mask"].to(device)
                is_small=batch["is_small"].to(device)
                optimizer.zero_grad()
                with autocast():
                    logits   = self.model(imgs)
                    loss_seg = self.seg_loss(logits, masks)
                    loss_rus = torch.tensor(0.0, device=device)
                    if self.use_rus:
                        p=torch.sigmoid(logits)
                        probs=torch.softmax(torch.cat([1-p,p],dim=1),dim=1)
                        loss_rus=self.rus_loss_fn(probs,masks,is_small)
                    loss=loss_seg+loss_rus
                scaler.scale(loss).backward()
                scaler.step(optimizer); scaler.update()
                m=compute_metrics(logits.detach(),masks)
                tot_loss+=loss.item(); tot_dice+=m["dice"]; n+=1
                loader_iter.set_postfix(loss=f"{loss.item():.4f}",
                                        dice=f"{m['dice']:.4f}")
            ep_dices.append(tot_dice/max(n,1))
            ep_losses.append(tot_loss/max(n,1))
        metrics={"train_dice":float(np.mean(ep_dices)),
                 "train_loss":float(np.mean(ep_losses)),
                 "client_id": self.cid}
        return self.get_parameters(config={}), len(self.trainloader.dataset), metrics

    def evaluate(self, parameters, config):
        self.set_parameters(parameters)
        self.model.eval()
        tot_loss=tot_dice=tot_sens=0.0; n=0
        with torch.no_grad():
            for batch in self.valloader:
                imgs=batch["image"].to(device); masks=batch["mask"].to(device)
                with autocast():
                    logits=self.model(imgs)
                    loss_val=self.seg_loss(logits,masks)
                m=compute_metrics(logits,masks)
                tot_loss+=loss_val.item(); tot_dice+=m["dice"]
                tot_sens+=m["sensitivity"]; n+=1
        return (float(tot_loss/max(n,1)),
                len(self.valloader.dataset),
                {"dice":float(tot_dice/max(n,1)),
                 "sensitivity":float(tot_sens/max(n,1))})

# ============================================================================
# 8. FEDAVG CORE
# ============================================================================
def fedavg_aggregate(client_sds, client_weights):
    total  = sum(client_weights)
    agg_sd = copy.deepcopy(client_sds[0])
    for key in agg_sd:
        agg_sd[key] = torch.zeros_like(agg_sd[key], dtype=torch.float32)
        for sd,w in zip(client_sds, client_weights):
            agg_sd[key] += sd[key].float()*(w/total)
    return agg_sd

def evaluate_global(model, loader):
    model.eval(); all_m=[]
    with torch.no_grad():
        for batch in loader:
            imgs=batch["image"].to(device); masks=batch["mask"].to(device)
            with autocast(): logits=model(imgs)
            all_m.append(compute_metrics(logits,masks))
    return {k:float(np.mean([m[k] for m in all_m])) for k in all_m[0]}

def run_fl_experiment(exp_name, client_dfs, test_loader,
                       n_rounds=20, n_local_epochs=2, use_rus=False,
                       noise_sigmas=None, resume=True):
    ckpt_path    = MODEL_DIR/f"{exp_name}_checkpoint.pth"
    best_path    = MODEL_DIR/f"{exp_name}_best.pth"
    hist_path    = MODEL_DIR/f"{exp_name}_history.json"
    cm_path      = MODEL_DIR/f"{exp_name}_client_metrics.json"

    client_loaders = build_client_loaders(client_dfs, noise_sigmas, augment_rare=True)
    client_sizes   = [len(df) for df in client_dfs]

    # Build Flower clients
    flower_clients = [
        NoduleClient(i, loader, test_loader, use_rus, n_local_epochs)
        for i, loader in enumerate(client_loaders)
    ]

    global_model = load_pretrained_unet()
    start_round  = 1; best_dice=0.0
    history      = defaultdict(list)
    client_hist  = defaultdict(lambda: defaultdict(list))

    # Mid-round checkpoint: saves after each client completes so a crash
    # mid-round (e.g. at client 4) resumes from that exact client.
    mid_ckpt_path = MODEL_DIR/f"{exp_name}_midround_checkpoint.pth"

    if resume and ckpt_path.exists():
        print(f"\n🔄 Resuming {exp_name} ...")
        ckpt = torch.load(ckpt_path, map_location=device)
        global_model.load_state_dict(ckpt["global_model_state_dict"])
        start_round = ckpt["round"]+1; best_dice=ckpt["best_dice"]
        if hist_path.exists():
            with open(hist_path) as f: history=defaultdict(list,json.load(f))
        if cm_path.exists():
            with open(cm_path) as f:
                raw=json.load(f)
                client_hist=defaultdict(lambda:defaultdict(list),
                             {k:defaultdict(list,v) for k,v in raw.items()})
        # Check if there is a mid-round checkpoint for the current start_round
        if mid_ckpt_path.exists():
            mid = torch.load(mid_ckpt_path, map_location=device)
            if mid["round"] == start_round:
                # Resume from within this round
                start_round      = mid["round"]         # same round, different client
                start_client_idx = mid["completed_client"] + 1
                partial_sds      = mid["partial_client_sds"]
                partial_sizes    = mid["partial_client_sizes"]
                global_model.load_state_dict(mid["global_model_state_dict"])
                best_dice        = mid["best_dice"]
                print(f"   ▸ Mid-round resume: Round {start_round}, "
                      f"starting from Client {start_client_idx}")
            else:
                start_client_idx = 0
                partial_sds      = []
                partial_sizes    = []
        else:
            start_client_idx = 0
            partial_sds      = []
            partial_sizes    = []
        print(f"   ▸ Round {start_round}/{n_rounds}  best_dice={best_dice:.4f}")
    else:
        print(f"\n🆕 Starting: {exp_name}")
        start_client_idx = 0
        partial_sds      = []
        partial_sizes    = []

    print("="*70)
    print(f"🚀 {exp_name.upper()}")
    print(f"   Rounds={n_rounds} | LocalEpochs={n_local_epochs} | Clients=5"
          f" | RUS={use_rus} | Hetero={'YES' if noise_sigmas else 'NO'}")
    print("="*70)

    for fl_round in range(start_round, n_rounds+1):
        print(f"\n🔁 Round {fl_round}/{n_rounds}")
        global_params = [v.cpu().numpy()
                         for v in global_model.state_dict().values()]

        # Restore partial results if resuming mid-round
        if fl_round == start_round and partial_sds:
            client_sds  = partial_sds
            round_dices = partial_sizes   # reuse var name for dices list
            resume_from = start_client_idx
            print(f"   ↩️  Resuming from Client {resume_from} "
                  f"({len(client_sds)} clients already done this round)")
        else:
            client_sds=[]; round_dices=[]; resume_from=0

        for client in flower_clients:
            if client.cid < resume_from:
                continue   # skip already-completed clients this round
            updated_params, n_samples, fit_m = client.fit(
                copy.deepcopy(global_params), {})
            keys = list(UNetModel().state_dict().keys())
            sd   = {k:torch.tensor(v) for k,v in zip(keys, updated_params)}
            client_sds.append(sd)
            d    = fit_m["train_dice"]; loss=fit_m["train_loss"]
            sig  = noise_sigmas[client.cid] if noise_sigmas else 15
            print(f"   Client {client.cid}: loss={loss:.4f} dice={d:.4f}"
                  f" σ={sig}HU n={n_samples}")
            client_hist[str(client.cid)]["round"].append(fl_round)
            client_hist[str(client.cid)]["dice"].append(float(d))
            client_hist[str(client.cid)]["loss"].append(float(loss))
            round_dices.append(float(d))
            torch.cuda.empty_cache()
            # Save mid-round checkpoint immediately after each client
            torch.save({
                "round":                   fl_round,
                "completed_client":        client.cid,
                "partial_client_sds":      client_sds,
                "partial_client_sizes":    round_dices,
                "global_model_state_dict": global_model.state_dict(),
                "best_dice":               best_dice,
            }, mid_ckpt_path)

        agg_sd = fedavg_aggregate(client_sds, client_sizes)
        global_model.load_state_dict(agg_sd)
        g = evaluate_global(global_model, test_loader)
        ece = compute_ece_scalar(global_model, test_loader)
        print(f"   ▶ Global: dice={g['dice']:.4f} sens={g['sensitivity']:.4f}"
              f" spec={g['specificity']:.4f} ECE={ece:.4f}"
              f" client_avg={np.mean(round_dices):.4f}")

        history["round"].append(fl_round)
        for k,v in g.items(): history[f"global_{k}"].append(v)
        history["global_ece"].append(ece)
        history["mean_client_dice"].append(float(np.mean(round_dices)))

        if g["dice"] > best_dice:
            best_dice = g["dice"]
            torch.save({"round":fl_round,
                        "global_model_state_dict":global_model.state_dict(),
                        "metrics":g,"ece":ece,"best_dice":best_dice}, best_path)
            print(f"   ⭐ NEW BEST dice={best_dice:.4f}")

        torch.save({"round":fl_round,
                    "global_model_state_dict":global_model.state_dict(),
                    "best_dice":best_dice}, ckpt_path)
        with open(hist_path,"w") as f: json.dump(dict(history),f,indent=2)
        with open(cm_path,"w") as f:
            json.dump({k:dict(v) for k,v in client_hist.items()},f,indent=2)
        # Round complete — delete mid-round checkpoint to avoid stale resume
        if mid_ckpt_path.exists():
            import os; os.remove(mid_ckpt_path)
        # Reset partial state for next round
        partial_sds=[]; partial_sizes=[]; resume_from=0

    print(f"\n✅ {exp_name} DONE | best_dice={best_dice:.4f}")
    return global_model, dict(history), {k:dict(v) for k,v in client_hist.items()}

# ============================================================================
# 9. STEP 8 — FL EXPERIMENT 1: IID FedAvg
# ============================================================================
print("\n"+"="*70)
print("STEP 8 — FL EXPERIMENT 1: IID FedAvg")
print("  5 clients | equal distribution | σ=15HU uniform | RUS=OFF")
print("="*70)

fl_iid_model, fl_iid_hist, fl_iid_chist = run_fl_experiment(
    "fl_iid_global", iid_client_dfs, test_loader,
    n_rounds=20, n_local_epochs=2, use_rus=False,
    noise_sigmas=None, resume=True)

# ============================================================================
# 10. STEP 9 — FL EXPERIMENT 2: Non-IID + Heterogeneous + RUS
# ============================================================================
print("\n"+"="*70)
print("STEP 9 — FL EXPERIMENT 2: Non-IID + Heterogeneous + RUS")
print("  Skewed 80%→20% small | σ=5,10,15,20,25 HU | RUS=ON")
print("="*70)

fl_noniid_model, fl_noniid_hist, fl_noniid_chist = run_fl_experiment(
    "fl_noniid_rus_global", noniid_client_dfs, test_loader,
    n_rounds=20, n_local_epochs=2, use_rus=True,
    noise_sigmas=CLIENT_NOISE_SIGMAS, resume=True)

# ============================================================================
# 11. STEP 10a — ABLATION: Non-IID WITHOUT RUS
# ============================================================================
print("\n"+"="*70)
print("STEP 10 — ABLATION: Non-IID WITHOUT RUS (10 rounds)")
print("  Same non-IID setup | RUS=OFF | purpose: measure ECE degradation")
print("="*70)

fl_norus_model, fl_norus_hist, _ = run_fl_experiment(
    "fl_noniid_norus_global", noniid_client_dfs, test_loader,
    n_rounds=10, n_local_epochs=2, use_rus=False,
    noise_sigmas=CLIENT_NOISE_SIGMAS, resume=True)

# ============================================================================
# 12. STEP 10b — STATISTICAL TESTS
# ============================================================================
print("\n"+"="*70)
print("STEP 10b — STATISTICAL ANALYSIS (McNemar + paired t-test)")
print("="*70)

def load_best(exp_name):
    p = MODEL_DIR/f"{exp_name}_best.pth"
    m = load_pretrained_unet(verbose=False)
    if p.exists():
        ckpt=torch.load(p,map_location=device)
        m.load_state_dict(ckpt["global_model_state_dict"])
    return m

m_iid   = load_best("fl_iid_global")
m_rus   = load_best("fl_noniid_rus_global")
m_norus = load_best("fl_noniid_norus_global")
m_cen   = load_pretrained_unet(verbose=False)

preds_iid,   tgts = collect_predictions(m_iid,   test_loader)
preds_rus,   _    = collect_predictions(m_rus,    test_loader)
preds_norus, _    = collect_predictions(m_norus,  test_loader)
preds_cen,   _    = collect_predictions(m_cen,    test_loader)

def mcnemar(pa, pb, tg, la, lb):
    ca=(pa==tg); cb=(pb==tg)
    b=((ca==True )&(cb==False)).sum()
    c=((ca==False)&(cb==True )).sum()
    chi2=(abs(b-c)-1)**2/(b+c+1e-8)
    p=float(scipy_stats.chi2.sf(chi2,df=1))
    sig="✅ p<0.05" if p<0.05 else "❌ ns"
    line=f"  McNemar [{la} vs {lb}]: b={b}, c={c}, χ²={chi2:.3f}, p={p:.4f} {sig}"
    print(line); return line

def ttest(da, db, la, lb):
    n=min(len(da),len(db))
    t,p=scipy_stats.ttest_rel(da[:n],db[:n])
    sig="✅ p<0.05" if p<0.05 else "❌ ns"
    line=f"  t-test [{la} vs {lb}]: t={t:.3f}, p={p:.4f} {sig}"
    print(line); return line

d_cen=dice_per_batch(m_cen,  test_loader)
d_iid=dice_per_batch(m_iid,  test_loader)
d_rus=dice_per_batch(m_rus,  test_loader)
d_nor=dice_per_batch(m_norus,test_loader)

stat_lines = ["="*60,"STATISTICAL TESTS","="*60,
              "\nMcNemar Tests (pixel-level):"]
stat_lines.append(mcnemar(preds_rus,  preds_norus, tgts, "FL+RUS","FL NoRUS"))
stat_lines.append(mcnemar(preds_iid,  preds_rus,   tgts, "FL IID", "FL+RUS"))
stat_lines.append(mcnemar(preds_cen,  preds_iid,   tgts, "Central","FL IID"))
stat_lines += ["\nPaired t-Tests (per-batch Dice):"]
stat_lines.append(ttest(d_rus, d_nor, "FL+RUS","FL NoRUS"))
stat_lines.append(ttest(d_iid, d_rus, "FL IID","FL+RUS"))
stat_lines.append(ttest(d_cen, d_iid, "Central","FL IID"))

stat_path = RESULTS_DIR/"fl_statistical_tests.txt"
with open(stat_path,"w") as f: f.write("\n".join(stat_lines))
print(f"\n📁 Statistical tests → {stat_path}")

# ============================================================================
# 13. ABLATION TABLE
# ============================================================================
print("\n"+"="*70)
print("ABLATION TABLE — Paper Table 2")
print("="*70)

def best_metrics(exp_name):
    p=MODEL_DIR/f"{exp_name}_best.pth"
    if p.exists():
        c=torch.load(p,map_location="cpu"); m=c.get("metrics",{})
        return {k:m.get(k,0) for k in ["dice","sensitivity","specificity",
                                         "precision","iou"]}|{"ece":c.get("ece",0),
                                                               "round":c.get("round",0)}
    return {k:0 for k in ["dice","sensitivity","specificity",
                            "precision","iou","ece","round"]}

central_ece = compute_ece_scalar(m_cen, test_loader)
mi=best_metrics("fl_iid_global")
mn=best_metrics("fl_noniid_rus_global")
mr=best_metrics("fl_noniid_norus_global")

abl_df = pd.DataFrame([
    {"Experiment":"Central U-Net","RUS":"No","Non-IID":"No",
     "Dice":0.8445,"Sensitivity":0.9089,"ECE":round(central_ece,4),
     "Best_Round":"ep64"},
    {"Experiment":"FL IID — FedAvg","RUS":"No","Non-IID":"No",
     "Dice":round(mi["dice"],4),"Sensitivity":round(mi["sensitivity"],4),
     "ECE":round(mi["ece"],4),"Best_Round":mi["round"]},
    {"Experiment":"FL Non-IID + RUS","RUS":"Yes","Non-IID":"Yes",
     "Dice":round(mn["dice"],4),"Sensitivity":round(mn["sensitivity"],4),
     "ECE":round(mn["ece"],4),"Best_Round":mn["round"]},
    {"Experiment":"FL Non-IID (no RUS)","RUS":"No","Non-IID":"Yes",
     "Dice":round(mr["dice"],4),"Sensitivity":round(mr["sensitivity"],4),
     "ECE":round(mr["ece"],4),"Best_Round":mr["round"]},
])
print(abl_df.to_string(index=False))
abl_path = RESULTS_DIR/"fl_ablation_table.csv"
abl_df.to_csv(abl_path, index=False)
print(f"\n📁 Ablation table → {abl_path}")

# ============================================================================
# 14. FIGURE 3 — FL LEARNING CURVES (Dice + Sensitivity + ECE per round)
# ============================================================================
print("\n📊 Figure 3: Learning Curves ...")
CDICE=0.8445; CSENS=0.9089

fig, axes = plt.subplots(2, 3, figsize=(18,10))
fig.suptitle("FL Learning Curves — Global Model", fontsize=15)

for col,(hist,title,color) in enumerate([
    (fl_iid_hist,   "FL IID (FedAvg)",       "steelblue"),
    (fl_noniid_hist,"FL Non-IID + RUS",       "darkorange"),
    (fl_norus_hist, "FL Non-IID (no RUS)",    "firebrick"),
]):
    rds=hist["round"]
    ax=axes[0,col]
    ax.plot(rds,hist["global_dice"],        color=color,lw=2,label="Dice")
    ax.plot(rds,hist["global_sensitivity"], color=color,lw=2,ls="--",label="Sensitivity")
    ax.axhline(CDICE,color="gray",ls=":",lw=1.5,label=f"Central Dice={CDICE}")
    ax.axhline(CSENS,color="silver",ls="-.",lw=1.5,label=f"Central Sens={CSENS}")
    ax.set_title(title,fontsize=12); ax.set_xlabel("FL Round"); ax.set_ylabel("Score")
    ax.set_ylim(0,1); ax.legend(fontsize=8); ax.grid(alpha=0.3)
    ax2=axes[1,col]
    ax2.plot(rds,hist["global_ece"],color=color,lw=2,label="ECE")
    ax2.axhline(0.10,color="red",ls=":",lw=1.5,label="Target ECE=0.10")
    ax2.axhline(central_ece,color="gray",ls=":",lw=1.5,
                label=f"Central ECE={central_ece:.3f}")
    ax2.set_title(f"{title} — ECE",fontsize=12); ax2.set_xlabel("FL Round")
    ax2.set_ylabel("ECE"); ax2.set_ylim(0,0.25)
    ax2.legend(fontsize=8); ax2.grid(alpha=0.3)

plt.tight_layout()
fig3=RESULTS_DIR/"fl_learning_curves.png"
plt.savefig(fig3,dpi=150,bbox_inches="tight"); plt.close()
print(f"  ✅ {fig3}")

# ============================================================================
# 15. FIGURE 3b — CLIENT DRIFT
# ============================================================================
print("📊 Figure 3b: Client Drift ...")
fig,axes=plt.subplots(1,2,figsize=(14,5))
fig.suptitle("Per-Client Local Dice Across FL Rounds",fontsize=13)
for ax,chist,title,cm_name in [
    (axes[0],fl_iid_chist,   "FL IID",          "Blues"),
    (axes[1],fl_noniid_chist,"FL Non-IID + RUS", "Oranges"),
]:
    cmap=plt.cm.get_cmap(cm_name,5)
    for cid in sorted(chist.keys(),key=int):
        ax.plot(chist[cid]["round"],chist[cid]["dice"],
                color=cmap(int(cid)+1),lw=2,label=f"Client {cid}")
    ax.axhline(CDICE,color="gray",ls=":",label="Central")
    ax.set_title(title); ax.set_xlabel("FL Round"); ax.set_ylabel("Local Dice")
    ax.set_ylim(0,1); ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
drift=RESULTS_DIR/"fl_client_drift.png"
plt.savefig(drift,dpi=150,bbox_inches="tight"); plt.close()
print(f"  ✅ {drift}")

# ============================================================================
# 16. FIGURE 4 — ECE COMPARISON (Paper Figure 4)
# ============================================================================
print("📊 Figure 4: ECE Comparison ...")
fig,axes=plt.subplots(1,2,figsize=(12,5))
fig.suptitle("Calibration (ECE) — Effect of RUS Loss",fontsize=13)
ax=axes[0]
ax.plot(fl_noniid_hist["round"],fl_noniid_hist["global_ece"],
        color="darkorange",lw=2,label="Non-IID + RUS")
ax.plot(fl_norus_hist["round"], fl_norus_hist["global_ece"],
        color="firebrick",lw=2,ls="--",label="Non-IID (no RUS)")
ax.axhline(0.10,color="green",ls=":",label="Target=0.10")
ax.set_xlabel("FL Round"); ax.set_ylabel("ECE")
ax.set_title("ECE vs FL Round"); ax.legend(); ax.grid(alpha=0.3)
ax2=axes[1]
lbls=["Central","FL IID","FL+RUS","FL NoRUS"]
eces=[central_ece,mi["ece"],mn["ece"],mr["ece"]]
cols=["steelblue","royalblue","darkorange","firebrick"]
bars=ax2.bar(lbls,eces,color=cols,alpha=0.85)
ax2.axhline(0.10,color="green",ls=":",lw=2,label="Target=0.10")
ax2.set_ylabel("ECE"); ax2.set_title("Final ECE per Experiment")
ax2.legend(); ax2.grid(alpha=0.3,axis="y")
for bar,v in zip(bars,eces):
    ax2.text(bar.get_x()+bar.get_width()/2,bar.get_height()+0.002,
             f"{v:.3f}",ha="center",va="bottom",fontsize=11)
plt.tight_layout()
ece_fig=RESULTS_DIR/"fl_ece_comparison.png"
plt.savefig(ece_fig,dpi=150,bbox_inches="tight"); plt.close()
print(f"  ✅ {ece_fig}")

# ============================================================================
# 17. FIGURE 6 — HETEROGENEITY BARS (Paper Figure 6)
# ============================================================================
print("📊 Figure 6: Heterogeneity Bars ...")
fig,axes=plt.subplots(1,2,figsize=(14,5))
fig.suptitle("Per-Client Dice (Final Round) — IID vs Non-IID+RUS",fontsize=13)
for ax,chist,title,color in [
    (axes[0],fl_iid_chist,   "FL IID",          "steelblue"),
    (axes[1],fl_noniid_chist,"FL Non-IID + RUS", "darkorange"),
]:
    cids=[str(i) for i in range(5)]
    fdices=[chist[cid]["dice"][-1] if chist.get(cid,{}).get("dice") else 0
            for cid in cids]
    bars=ax.bar([f"C{cid}" for cid in cids],fdices,color=color,alpha=0.85)
    ax.axhline(CDICE,color="gray",ls=":",lw=2,label=f"Central={CDICE}")
    ax.set_xlabel("Client"); ax.set_ylabel("Dice (final round)")
    ax.set_title(title); ax.set_ylim(0,1); ax.legend(); ax.grid(alpha=0.3,axis="y")
    for bar,v in zip(bars,fdices):
        ax.text(bar.get_x()+bar.get_width()/2,bar.get_height()+0.01,
                f"{v:.3f}",ha="center",va="bottom",fontsize=10)
    if "Non-IID" in title:
        for i,sig in enumerate(CLIENT_NOISE_SIGMAS):
            ax.text(i,-0.07,f"σ={sig}",ha="center",fontsize=9,
                    transform=ax.get_xaxis_transform())
plt.tight_layout()
hetero=RESULTS_DIR/"fl_heterogeneity_bars.png"
plt.savefig(hetero,dpi=150,bbox_inches="tight"); plt.close()
print(f"  ✅ {hetero}")

# ============================================================================
# 18. FINAL SUMMARY
# ============================================================================
print("\n"+"="*70)
print("COMPLETE SUMMARY — Steps 7–10")
print("="*70)
print(abl_df.to_string(index=False))

print("\n📁 ALL OUTPUTS ON GOOGLE DRIVE:")
for folder,fname,desc in [
    (MODEL_DIR,  "fl_iid_global_best.pth",             "FL-IID best model"),
    (MODEL_DIR,  "fl_noniid_rus_global_best.pth",       "FL-NonIID+RUS best model"),
    (MODEL_DIR,  "fl_noniid_norus_global_best.pth",     "Ablation best model"),
    (MODEL_DIR,  "fl_iid_global_history.json",          "FL-IID round metrics"),
    (MODEL_DIR,  "fl_noniid_rus_global_history.json",   "FL-NonIID+RUS metrics"),
    (MODEL_DIR,  "fl_iid_global_client_metrics.json",   "FL-IID client metrics"),
    (MODEL_DIR,  "fl_noniid_rus_global_client_metrics.json","NonIID+RUS client metrics"),
    (RESULTS_DIR,"fl_ablation_table.csv",               "← Paper Table 2"),
    (RESULTS_DIR,"fl_statistical_tests.txt",            "← McNemar + t-test"),
    (RESULTS_DIR,"fl_learning_curves.png",              "← Paper Figure 3"),
    (RESULTS_DIR,"fl_client_drift.png",                 "← Paper Figure 3b"),
    (RESULTS_DIR,"fl_ece_comparison.png",               "← Paper Figure 4"),
    (RESULTS_DIR,"fl_heterogeneity_bars.png",           "← Paper Figure 6"),
]:
    ok="✅" if (folder/fname).exists() else "⚠️ "
    print(f"  {ok} {folder/fname}  {desc}")

print("\n🎉 STEPS 7–10 COMPLETE!")
print("   NEXT → Steps 11-12 : Grad-CAM++ XAI   (no GPU training needed)")
print("   NEXT → Steps 13-14 : LUNA16 FROC eval  (inference only)")